name: WordPress Theme Code Check

on: [push, pull_request]

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: install PHP_CodeSniffer
          run: composer global require "squizlabs/php_codesniffer=*"
        - name: install WordPress Coding Standards
          run: |
            composer global require wp-coding-standards/wpcs
            /home/runner/.composer/vendor/bin/phpcs --config-set installed_paths /home/runner/.composer/vendor/wp-coding-standards/wpcs
        - name: check coding
          run: /home/runner/.composer/vendor/bin/phpcs --standard=WordPress ./*.php

